/**
 * Demo Data for OWN IT
 * This data is used when API services are not available
 */

export const DEMO_WARDROBE = [
  {
    id: '1',
    name: 'Cream Linen Shirt',
    category: 'tops',
    subcategory: 'shirts',
    color: 'cream',
    colors: ['cream'],
    pattern: 'solid',
    material: 'linen',
    style: 'minimalist',
    occasions: ['work', 'casual', 'dinner'],
    seasons: ['spring', 'summer', 'autumn'],
    imageUrl: 'https://images.unsplash.com/photo-1598033129519-0c5ddef81f67?w=500&h=500&fit=crop',
    isFavorite: true,
    wearFrequency: 75,
    outfitIds: ['o1', 'o2'],
    lastWorn: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Black Wide-Leg Trousers',
    category: 'bottoms',
    subcategory: 'pants',
    color: 'deep-brown',
    colors: ['deep-brown', 'black'],
    pattern: 'solid',
    material: 'wool',
    style: 'formal',
    occasions: ['work', 'formal', 'dinner'],
    seasons: ['autumn', 'winter', 'spring'],
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    isFavorite: true,
    wearFrequency: 80,
    outfitIds: ['o1', 'o3'],
    lastWorn: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Camel Overcoat',
    category: 'outerwear',
    subcategory: 'jackets',
    color: 'warm-beige',
    colors: ['warm-beige'],
    pattern: 'solid',
    material: 'wool',
    style: 'elegant',
    occasions: ['work', 'casual', 'formal'],
    seasons: ['autumn', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1539533057440-7cc4a5d60df9?w=500&h=500&fit=crop',
    isFavorite: true,
    wearFrequency: 60,
    outfitIds: ['o2'],
    lastWorn: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'White Sneakers',
    category: 'shoes',
    subcategory: 'shoes',
    color: 'cream',
    colors: ['cream', 'white'],
    pattern: 'solid',
    material: 'leather',
    style: 'casual',
    occasions: ['casual', 'college', 'gym'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    isFavorite: true,
    wearFrequency: 90,
    outfitIds: ['o1', 'o4'],
    lastWorn: new Date(Date.now() - 0 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Burgundy Knit Sweater',
    category: 'tops',
    subcategory: 'shirts',
    color: 'muted-burgundy',
    colors: ['muted-burgundy'],
    pattern: 'solid',
    material: 'wool',
    style: 'elegant',
    occasions: ['work', 'casual', 'dinner'],
    seasons: ['autumn', 'winter', 'spring'],
    imageUrl: 'https://images.unsplash.com/photo-1552062407-291826ab63fd?w=500&h=500&fit=crop',
    isFavorite: false,
    wearFrequency: 45,
    outfitIds: ['o3'],
    lastWorn: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Olive Chinos',
    category: 'bottoms',
    subcategory: 'pants',
    color: 'olive',
    colors: ['olive'],
    pattern: 'solid',
    material: 'cotton',
    style: 'casual',
    occasions: ['casual', 'college', 'travel'],
    seasons: ['spring', 'summer', 'autumn'],
    imageUrl: 'https://images.unsplash.com/photo-1473621038790-db4d28c8c6e4?w=500&h=500&fit=crop',
    isFavorite: false,
    wearFrequency: 55,
    outfitIds: ['o4'],
    lastWorn: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Brown Leather Bag',
    category: 'bags',
    subcategory: 'bags',
    color: 'deep-brown',
    colors: ['deep-brown'],
    pattern: 'solid',
    material: 'leather',
    style: 'elegant',
    occasions: ['work', 'casual', 'formal'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop',
    isFavorite: true,
    wearFrequency: 85,
    outfitIds: ['o1', 'o2', 'o3'],
    lastWorn: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Gold Watch',
    category: 'watches',
    subcategory: 'watches',
    color: 'soft-gold',
    colors: ['soft-gold'],
    pattern: 'solid',
    material: 'gold',
    style: 'elegant',
    occasions: ['work', 'formal', 'dinner', 'date'],
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=500&h=500&fit=crop',
    isFavorite: true,
    wearFrequency: 70,
    outfitIds: ['o1', 'o2', 'o3'],
    lastWorn: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
]

export const DEMO_OUTFITS = [
  {
    id: 'o1',
    name: 'Minimalist Work',
    itemIds: ['1', '2', '4', '7', '8'],
    mood: 'confident',
    occasion: 'work',
    style: 'minimalist',
    description: 'Clean, professional, and effortless.',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    isFavorite: true,
    isRecent: true,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'o2',
    name: 'Elegant Evening',
    itemIds: ['1', '3', '7', '8'],
    mood: 'elegant',
    occasion: 'dinner',
    style: 'elegant',
    description: 'Sophisticated and timeless.',
    imageUrl: 'https://images.unsplash.com/photo-1539533057440-7cc4a5d60df9?w=500&h=500&fit=crop',
    isFavorite: true,
    isRecent: false,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'o3',
    name: 'Cozy Autumn',
    itemIds: ['5', '2', '3', '7'],
    mood: 'calm',
    occasion: 'casual',
    style: 'elegant',
    description: 'Warm and comfortable.',
    imageUrl: 'https://images.unsplash.com/photo-1552062407-291826ab63fd?w=500&h=500&fit=crop',
    isFavorite: false,
    isRecent: true,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'o4',
    name: 'Casual Weekend',
    itemIds: ['1', '6', '4', '7'],
    mood: 'relaxed',
    occasion: 'casual',
    style: 'casual',
    description: 'Comfortable and laid-back.',
    imageUrl: 'https://images.unsplash.com/photo-1473621038790-db4d28c8c6e4?w=500&h=500&fit=crop',
    isFavorite: false,
    isRecent: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
]

export const DEMO_USER = {
  id: 'demo-user-1',
  email: 'demo@ownit.com',
  username: 'demouser',
  firstName: 'Alex',
  lastName: 'Fashion',
  profile: {
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    style: 'minimalist',
    colors: ['cream', 'deep-brown', 'olive'],
    aesthetic: 'elegant',
    onboardingComplete: true,
  },
  createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000),
  updatedAt: new Date(),
}
